name: Publish to PyPI

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install necessary tools
        run: |
          python -m pip install --upgrade setuptools wheel twine

      - name: Create source and wheel distributions
        run: python setup.py sdist bdist_wheel
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
    # - name: Check out the repository
    #   uses: actions/checkout@v2

    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.x

    # - name: Install necessary tools
    #   run: |
    #     python -m pip install --upgrade setuptools wheel twine

    # - name: Create source and wheel distributions
    #   run: python setup.py sdist bdist_wheel

    # - name: Upload to PyPI
    #   run: twine upload dist/* -u robotical -p ${{ secrets.PYPI_PASSWORD }}
